#!/usr/bin/env python3
"""
validate_alignment.py
=====================
Prototype script for testing alignment scoring logic.
Compares detected keypoints against template keypoints
and returns an alignment score (0.0 - 1.0).

This logic will eventually run on-device in Dart/Swift,
but we prototype here for rapid iteration.
"""

import math
import json
import sys


# === Template Keypoints (normalized 0-1 coordinates) ===
# These match the wireframe templates generated by generate_wireframes.py
TEMPLATE_KEYPOINTS = {
    "front_left_45": {
        "front_wheel": [0.278, 0.375],
        "rear_wheel": [0.741, 0.375],
        "a_pillar": [0.352, 0.167],
        "c_pillar": [0.722, 0.167],
        "headlight": [0.139, 0.271],
        "roof_peak": [0.509, 0.146],
    },
    "side_driver": {
        "front_wheel": [0.208, 0.375],
        "rear_wheel": [0.718, 0.375],
        "a_pillar": [0.278, 0.167],
        "c_pillar": [0.722, 0.208],
        "headlight": [0.093, 0.260],
        "taillight": [0.852, 0.260],
    },
    "rear_center": {
        "left_wheel": [0.222, 0.370],
        "right_wheel": [0.704, 0.370],
        "left_taillight": [0.241, 0.266],
        "right_taillight": [0.685, 0.266],
        "roof_center": [0.463, 0.156],
    },
}

# Maximum allowed distance (normalized) for a keypoint to count as "aligned"
MAX_KEYPOINT_DISTANCE = 0.08  # 8% of frame dimension


def euclidean_distance(p1, p2):
    """Calculate euclidean distance between two 2D points."""
    return math.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)


def calculate_alignment_score(template_name, detected_keypoints):
    """
    Calculate alignment score between detected keypoints and template.
    
    Args:
        template_name: Name of the template (e.g., "front_left_45")
        detected_keypoints: Dict of {keypoint_name: [x, y]} in normalized coords
    
    Returns:
        float: Alignment score between 0.0 and 1.0
        dict: Per-keypoint alignment details
    """
    if template_name not in TEMPLATE_KEYPOINTS:
        raise ValueError(f"Unknown template: {template_name}")

    template = TEMPLATE_KEYPOINTS[template_name]
    total_score = 0.0
    matched = 0
    details = {}

    for kp_name, template_pos in template.items():
        if kp_name in detected_keypoints:
            detected_pos = detected_keypoints[kp_name]
            distance = euclidean_distance(template_pos, detected_pos)

            # Score: 1.0 if perfectly aligned, 0.0 if at max distance
            kp_score = max(0.0, 1.0 - (distance / MAX_KEYPOINT_DISTANCE))
            total_score += kp_score
            matched += 1

            details[kp_name] = {
                "template": template_pos,
                "detected": detected_pos,
                "distance": round(distance, 4),
                "score": round(kp_score, 3),
                "aligned": kp_score > 0.8,
            }
        else:
            details[kp_name] = {
                "template": template_pos,
                "detected": None,
                "distance": None,
                "score": 0.0,
                "aligned": False,
            }

    # Final score = average of all keypoints (missing ones count as 0)
    alignment_score = total_score / len(template) if template else 0.0

    return round(alignment_score, 3), details


def generate_instructions(alignment_score, details):
    """
    Generate user-facing instructions based on alignment analysis.
    
    Returns:
        str: Instruction text to display on screen
    """
    if alignment_score >= 0.90:
        return "✅ Perfect! Hold still..."
    
    if alignment_score >= 0.75:
        return "Almost there! Fine-tune your position."

    # Find the worst-aligned keypoint and suggest correction
    worst_kp = None
    worst_score = 1.0
    for kp_name, info in details.items():
        if info["score"] < worst_score and info["detected"] is not None:
            worst_score = info["score"]
            worst_kp = kp_name

    if worst_kp and details[worst_kp]["detected"] is not None:
        template_pos = details[worst_kp]["template"]
        detected_pos = details[worst_kp]["detected"]
        dx = template_pos[0] - detected_pos[0]
        dy = template_pos[1] - detected_pos[1]

        if abs(dx) > abs(dy):
            direction = "right" if dx > 0 else "left"
            return f"Move {direction} — align the {worst_kp.replace('_', ' ')}"
        else:
            direction = "back" if dy > 0 else "closer"
            return f"Step {direction} — align the {worst_kp.replace('_', ' ')}"

    # Missing keypoints
    missing = [k for k, v in details.items() if v["detected"] is None]
    if missing:
        return f"Can't see: {', '.join(missing)}. Adjust your angle."

    return "Align the vehicle with the overlay."


# === Demo / Test ===
def demo():
    """Run a demo alignment check with simulated keypoints."""
    print("=== Alignment Validation Demo ===\n")

    # Simulated detected keypoints (slightly off from template)
    test_cases = [
        {
            "name": "Good alignment",
            "template": "front_left_45",
            "keypoints": {
                "front_wheel": [0.28, 0.38],
                "rear_wheel": [0.74, 0.37],
                "a_pillar": [0.35, 0.17],
                "c_pillar": [0.72, 0.17],
                "headlight": [0.14, 0.27],
                "roof_peak": [0.51, 0.15],
            },
        },
        {
            "name": "Poor alignment (too far right)",
            "template": "front_left_45",
            "keypoints": {
                "front_wheel": [0.40, 0.38],
                "rear_wheel": [0.85, 0.37],
                "a_pillar": [0.45, 0.17],
                "c_pillar": [0.82, 0.17],
                "headlight": [0.25, 0.27],
                "roof_peak": [0.62, 0.15],
            },
        },
        {
            "name": "Missing keypoints",
            "template": "side_driver",
            "keypoints": {
                "front_wheel": [0.21, 0.38],
                "rear_wheel": [0.72, 0.38],
            },
        },
    ]

    for case in test_cases:
        print(f"--- {case['name']} ---")
        score, details = calculate_alignment_score(case["template"], case["keypoints"])
        instruction = generate_instructions(score, details)

        print(f"  Template: {case['template']}")
        print(f"  Score: {score:.1%}")
        print(f"  Instruction: {instruction}")
        print(f"  Auto-capture: {'YES ✅' if score >= 0.90 else 'NO ❌'}")

        for kp, info in details.items():
            status = "✅" if info["aligned"] else "❌"
            if info["detected"]:
                print(f"    {status} {kp}: score={info['score']:.1%}, dist={info['distance']:.4f}")
            else:
                print(f"    ❌ {kp}: NOT DETECTED")
        print()


if __name__ == "__main__":
    demo()
